export const config: any = {
  items: [
    {
      text: '25.05.2021',
      labelText: 'Вывоз метала',
      span: 'А454А1с2',
      color: '#FAAC0F',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А454А1с2',
      color: '#FAAC0F',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'Е8рпЕ4',
      color: '#FAAC0F',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А454А1с2',
      color: '#FAAC0F',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А458А2с',
      color: '#FAAC0F',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'Н4в5Н45',
      color: '#FAAC0F',
      link: '/cargo_details',
    },
  ],
  items2: [
    {
      text: '25.05.2021',
      labelText: 'Вывоз метала',
      span: 'А454А1с2',
      color: '#00AF43',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А454А1с2',
      color: '#00AF43',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'Е8рпЕ4',
      color: '#00AF43',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А454А1с2',
      color: '#00AF43',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А458А2с',
      color: '#00AF43',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'Н4в5Н45',
      color: '#00AF43',
      link: '/cargo_details',
    },
  ],
  items3: [
    {
      text: '25.05.2021',
      labelText: 'Вывоз метала',
      span: 'А454А1с2',
      color: '#E051AF',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А454А1с2',
      color: '#E051AF',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'Е8рпЕ4',
      color: '#E051AF',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А454А1с2',
      color: '#E051AF',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'А458А2с',
      color: '#E051AF',
      link: '/cargo_details',
    },
    {
      text: '25.05.2021',
      labelText: 'Крановые работы',
      span: 'Н4в5Н45',
      color: '#E051AF',
      link: '/cargo_details',
    },
  ],
}
